# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sanu Satyadarshi
tagline:          'Software Engineer'
description:      'I am a Software Engineer'
url:              https://sanusatyadarshi.com
baseurl:          /

author:
  name:           'Sanu Satyadarshi'
  url:            https://sanusatyadarshi.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sanusatyadarshi
